### ISSUE TITLE
WifiNetworkSuggestion not work..help me

### ISSUE THREAD

**Issue by AmirAmraei** [AndrewEfimov/Wrappers#1]
var
{$IF DEFINED(ANDROID)}
  WifiManager: JWifiManager;
  WifiConfiguration: JWifiNetworkSuggestion_Builder;
  netID: integer;
  List: JList;
{$ENDIF}
begin
     {$IF DEFINED(ANDROID)}
       WifiConfiguration := TJWifiNetworkSuggestion_Builder.JavaClass.init;

       WifiConfiguration.setSsid(StringToJString('"TEST6"'));
       WifiConfiguration.setWpa2Passphrase(StringToJString('"12345678"'));
       WifiConfiguration.build;

       List := TJList.Wrap(WifiConfiguration);

       WifiManager := TJWifiManager.Wrap(TAndroidHelper.Context.getSystemService(TJContext.JavaClass.WIFI_SERVICE));
       netID := WifiManager.addNetworkSuggestions(List);
end;

this code not work and show error, why?
can you help me?

**Comment by AndrewEfimov** [comment]
what is the error text?

**Comment by AndrewEfimov** [comment]
what is the error text?

See help: 
[https://developer.android.com/guide/topics/connectivity/wifi-suggest#java](https://developer.android.com/guide/topics/connectivity/wifi-suggest#java)
and
[https://developer.android.com/reference/android/net/wifi/WifiNetworkSuggestion.Builder#build()](https://developer.android.com/reference/android/net/wifi/WifiNetworkSuggestion.Builder#build())
and
[https://developer.android.com/reference/android/net/wifi/WifiManager#addNetworkSuggestions(java.util.List%3Candroid.net.wifi.WifiNetworkSuggestion%3E)](https://developer.android.com/reference/android/net/wifi/WifiManager#addNetworkSuggestions(java.util.List%3Candroid.net.wifi.WifiNetworkSuggestion%3E))

Pay attention to the types of variables and the values assigned to them in examples from the help:
`WifiNetworkSuggestion suggestion2 =
new WifiNetworkSuggestion.Builder()
...`
and
`List<WifiNetworkSuggestion> suggestionsList =
new ArrayList<WifiNetworkSuggestion> {{
...`

There are errors in your code.

In Delphi, your code would look something like this:
```
var
  WifiNetworkSuggestion_Builder: JWifiNetworkSuggestion_Builder;
  WifiNetworkSuggestion: JWifiNetworkSuggestion;
  ArrayList: JArrayList;
  List: JList;
  WifiManager: JWifiManager;
  netID: Integer;
begin
  WifiNetworkSuggestion_Builder := TJWifiNetworkSuggestion_Builder.JavaClass.init;
  WifiNetworkSuggestion_Builder.setSsid(StringToJString('"TEST6"'));
  WifiNetworkSuggestion_Builder.setWpa2Passphrase(StringToJString('"12345678"'));

  WifiNetworkSuggestion := WifiNetworkSuggestion_Builder.build;

  ArrayList := TJArrayList.JavaClass.init;
  ArrayList.add(WifiNetworkSuggestion);

  List := TJList.Wrap(ArrayList);

  WifiManager := TJWifiManager.Wrap(TAndroidHelper.context.getSystemService(TJContext.JavaClass.WIFI_SERVICE));
  netID := WifiManager.AddNetworkSuggestions(List);
end;
```

And make sure you've requested all the necessary permissions.

**Comment by AmirAmraei** [comment]
very tnk for replay
worked with your code and WifiManager.AddNetworkSuggestions(List); returned 0;
but i cant find in Saved networks

**Comment by AndrewEfimov** [comment]
This code works for me.
I use my Wi-Fi name and password (after deleting the network in the settings), I press the button in the app and the phone automatically connects to my Wi-Fi. Most importantly, my Wi-Fi is not in the list of saved networks. When the phone connected to my Wi-Fi, it showed me additional text "Connecting Suggested App My App Name". If you uninstall the application, the phone stops connecting to this network.

Try specifying the network name and password without the double quotes:
```
  WifiNetworkSuggestion_Builder.setSsid(StringToJString('TEST6'));
  WifiNetworkSuggestion_Builder.setWpa2Passphrase(StringToJString('12345678'));
```

My Wi-Fi wrapper works.
To understand what is happening, you need to study the help in more detail.

**Update**. Open help: [https://developer.android.com/guide/topics/connectivity/wifi-suggest](https://developer.android.com/guide/topics/connectivity/wifi-suggest)
There is a note at the very beginning:

> Note: Wi-Fi suggestions are not saved networks and will not appear in the saved network page. To add a new Wi-Fi network with user completion, see the [ACTION_WIFI_ADD_NETWORKS](https://developer.android.com/reference/android/provider/Settings#ACTION_WIFI_ADD_NETWORKS) activity action API. This API will prompt the user to approve the network addition.

**Comment by AmirAmraei** [comment]
i tested without the double quotes And because there is no error, in this case, it does not show more details
just WifiManager.AddNetworkSuggestions(List); returned 0;
can you send me your sample code?
I do not know Java language

**Comment by AndrewEfimov** [comment]
This is your corrected code, it works for me:

```
var
  WifiNetworkSuggestion_Builder: JWifiNetworkSuggestion_Builder;
  WifiNetworkSuggestion: JWifiNetworkSuggestion;
  ArrayList: JArrayList;
  List: JList;
  WifiManager: JWifiManager;
  netID: Integer;
begin
  // permission request response android.permission.ACCESS_FINE_LOCATION
  if (Length(AGrantResults) = 1) and (AGrantResults[0] = TPermissionStatus.Granted) then
  begin
    WifiNetworkSuggestion_Builder := TJWifiNetworkSuggestion_Builder.JavaClass.init;
    WifiNetworkSuggestion_Builder.setSsid(StringToJString('Name'));
    WifiNetworkSuggestion_Builder.setWpa2Passphrase(StringToJString('Pass'));

    WifiNetworkSuggestion := WifiNetworkSuggestion_Builder.build;

    ArrayList := TJArrayList.JavaClass.init;
    ArrayList.add(WifiNetworkSuggestion);

    List := TJList.Wrap(ArrayList);

    WifiManager := TJWifiManager.Wrap(TAndroidHelper.context.getSystemService(TJContext.JavaClass.WIFI_SERVICE));
    netID := WifiManager.AddNetworkSuggestions(List);
  end;
```

**Comment by AmirAmraei** [comment]
Thanks and I will test

**Comment by AmirAmraei** [comment]
So why does it not work for me?
https://dl.turbodigital.ir/index.php?share/file&user=1&sid=yCmtv37z

(Full Code)

**Comment by AndrewEfimov** [comment]
> So why does it not work for me?
I don't know why it doesn't work for you.
Read the help and use Debug mode (Android Device Monitor) for your application.

Here is my test app (based on [https://github.com/AndrewEfimov/FMX-Android-API-Examples/tree/master/WifiTestAPI](https://github.com/AndrewEfimov/FMX-Android-API-Examples/tree/master/WifiTestAPI)):
[TestSuggestions.zip](https://github.com/AndrewEfimov/Wrappers/files/8711589/TestSuggestions.zip)

**Comment by AndrewEfimov** [comment]
> So why does it not work for me?

I don't know why it doesn't work for you.
Read the help and use Debug mode (Android Device Monitor) for your application.

Here is my test app (based on [https://github.com/AndrewEfimov/FMX-Android-API-Examples/tree/master/WifiTestAPI](https://github.com/AndrewEfimov/FMX-Android-API-Examples/tree/master/WifiTestAPI)):

Test app: [TestSuggestions.zip](https://github.com/AndrewEfimov/Wrappers/files/8712231/TestSuggestions.zip)

**Comment by AndrewEfimov** [comment]
> So why does it not work for me?

I don't know why it doesn't work for you.
Read the help and use Debug mode (Android Device Monitor) for your application.

Here is my test app (based on [https://github.com/AndrewEfimov/FMX-Android-API-Examples/tree/master/WifiTestAPI](https://github.com/AndrewEfimov/FMX-Android-API-Examples/tree/master/WifiTestAPI)):

Test app: [TestSuggestions.zip](https://github.com/AndrewEfimov/Wrappers/files/8712352/TestSuggestions.zip)

**Comment by AmirAmraei** [comment]
hello
After 18 months
![per](https://github.com/AndrewEfimov/Wrappers/assets/11356930/cde98ee5-aa4e-41f2-ac6b-0a7c38bd03ac)
It just needed this permission 😂
